// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/1/2025, 6:19:17 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/heathcliff/Downloads/devsite/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/heathcliff/Downloads/devsite/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/heathcliff/Downloads/devsite/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/heathcliff/Downloads/devsite/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/heathcliff/Downloads/devsite/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/heathcliff/Downloads/devsite/app/plugins/**/*.{js,ts,mjs}","/Users/heathcliff/Downloads/devsite/composables/**/*.{js,ts,mjs}","/Users/heathcliff/Downloads/devsite/utils/**/*.{js,ts,mjs}","/Users/heathcliff/Downloads/devsite/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/heathcliff/Downloads/devsite/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/heathcliff/Downloads/devsite/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;